routes/web.php
        Route::post('formacao/update', ['uses' => 'Curriculos\Farmaceuticos\FormacaoController@update']);
        Route::resource( 'deficiencia', 'Curriculos\Farmaceuticos\DeficienciaController');
        Route::post('deficiencia/update', ['uses' => 'Curriculos\Farmaceuticos\DeficienciaController@update']);
        Route::resource( 'extracurso', 'Curriculos\Farmaceuticos\ExtracursoController');
        Route::post('extracurso/update', ['uses' => 'Curriculos\Farmaceuticos\ExtracursoController@update']);
        Route::resource( 'idioma', 'Curriculos\Farmaceuticos\IdiomaController');
        Route::post('idioma/update', ['uses' => 'Curriculos\Farmaceuticos\IdiomaController@update']);
        Route::resource( 'interesse', 'Curriculos\Farmaceuticos\InteresseController');
        Route::post('interesse/update', ['uses' => 'Curriculos\Farmaceuticos\InteresseController@update']);
        Route::resource( 'experiencia', 'Curriculos\Farmaceuticos\ExperienciaController');
        Route::post('experiencia/update', ['uses' => 'Curriculos\Farmaceuticos\ExperienciaController@update']);
        Route::get( 'meusdados', ['uses' => 'Curriculos\Farmaceuticos\CurriculoController@perfilfarmaceutico', 'as' => 'Curriculo.perfilfarmaceutico']);


    });

    /**
     * Curriculos/Empresas  com login
     */
    Route::group( [ 'as' => 'empresas.', 'prefix' => 'empresas', 'middleware' => 'IsEmpresa'], function() {

        /**
         * Home
         */
        Route::get('/',['as' => 'home', function() {
            return View::make('site::Curriculos.empresas.home');
        }]);
        Route::resource( 'empresa', 'Curriculos\Empresas\EmpresaController');
        Route::post('empresa/update', ['uses' => 'Curriculos\Empresas\EmpresaController@update']);
        Route::post('empresa/{id}/disable', ['uses' => 'Curriculos\Empresas\EmpresaController@disable', 'as' => 'empresa.disable']);

        Route::resource( 'vaga', 'Curriculos\Empresas\VagaController');
        Route::post('vaga/update', ['uses' => 'Curriculos\Empresas\VagaController@update']);
        Route::resource( 'pesquisa', 'Curriculos\Empresas\PesquisacvController');
        Route::post('pesquisa/update', ['uses' => 'Curriculos\Empresas\PesquisacvController@update']);
        Route::resource( 'estatisticavagas', 'Curriculos\Empresas\EstatisticavagasController');
        Route::post('desabilitarvaga/{id}/active', ['uses' => 'Curriculos\Empresas\EstatisticavagasController@disable', 'as' => 'estatisticavagas.disable']);


        /**
        * Sobre
        */
        Route::get( 'sobre', 'PagesController@sobre' );
        });
        });






/***********************************************************
 * -------------------------------------------------------------------------
 *  PAF-Descontos
 * -------------------------------------------------------------------------
 */

/**
 * Descontos
 */
Route::resource('descontos', 'DescontoController');
Route::get( 'empresas', ['uses' => 'DescontoController@empresa', 'as' => 'empresa']);

 /**
  * Usuario Inativo
  */
    Route::get( 'usuarioinativo', 'PagesController@usuarioinativo' );


 /***********************************************************
 * -------------------------------------------------------------------------
 *  Envio de Contatos
 * -------------------------------------------------------------------------
 */
Route::get('contato', ['as' => 'contato', 'uses' => 'ContatoController@create' ]);
Route::get( 'contato/serparceiro', ['uses' => 'ContatoController@serparceiro', 'as' => 'serparceiro']);
Route::get( 'contato/indicarparceiro', ['uses' => 'ContatoController@indicarparceiro', 'as' => 'indicarparceiro']);
Route::get( 'contato/retiraranuncio', ['uses' => 'ContatoController@retiraranuncio', 'as' => 'retiraranuncio']);
Route::post('contato', ['as' => 'contato.store', 'uses' => 'ContatoController@store' ]);

/***********************************************************
 * -------------------------------------------------------------------------
 *  Cidades do Brasil
 * -------------------------------------------------------------------------
 */
Route::get( '/ufs/', function( $uf = null ) {
    return response() -> json( App\Cidade::select( 'TT008CC001' ) -> distinct('TT008CC001') -> orderBy('TT008CC001') -> get());
});

Route::get( '/cidades/{uf}', function( $uf = null ) {
    return response() -> json( App\Cidade::where( 'TT008CC001', $uf ) -> orderBy('TT008CC003') -> get());
});

/**
 * Teste Email
 */
Route::get( 'email', 'PagesController@email' );



//TESTES DE LOGIN E PERFIL////////////////////////////////////////////////////////////


Route::get( '/teste', function () {

 $user = Auth::user();

    if($user->isAdmin()){
        echo "Logado como Admin";

    }
    if($user->isFarmaceutico()){
        echo "Logado como Farmaceutico";

    }
    if($user->isEmpresa()){
        echo "Logado como Empresa";

    }

});

/***********************************************************
 * -------------------------------------------------------------------------
 *  Cadastro de Farmaceuticos
 * -------------------------------------------------------------------------
 */ 

        /**
         * Digitar o CPF
         */
Route::resource( 'cadastro', 'Soap\SoapController' );
Route::post('inserirCRF', 'Soap\SoapController@buscasoap')->name('cadastro.buscasoap');
Route::post('inserirEmail', 'Soap\SoapController@validacrf')->name('cadastro.validacrf');
Route::get('pfs', 'Soap\SoapController@pfs');
Route::post('enviaemail', ['as' => 'cadastro.enviaemail', 'uses' => 'Soap\SoapController@enviaemail' ]);
//Route::get( 'enviaemail', 'Soap\SoapController@enviaemail')->name('cadastro.enviaemail');


//Route::get( 'admin2/user/roles', ['middleware'=> ['web'], function () {
//
//    return "Middleware role";
//}  ]);

Route::get( '/admin2', 'AdminController@index');

//TESTES DE LOGIN E PERFIL////////////////////////////////////////////////////////////


/***********************************************************
 * -------------------------------------------------------------------------
 *  Painel Administrador
 * -------------------------------------------------------------------------
 */
Route::group([ 'as' => 'admin.', 'prefix' => 'admin',  'middleware' => ['auth', 'IsAdmin']], function() {

    /**
    * Home
    */
    Route::get('/',['as' => 'home', function() {
        return View::make('admin::home');
    }]);

    /**
    * Artigos
    */
    Route::resource( 'artigos', 'Admin\ArtigoController' );
    Route::post('artigo/{id}/active', ['uses' => 'Admin\ArtigoController@active', 'as' => 'artigos.active']);

    /**
    * Banners
    */
    Route::resource( 'banners', 'Admin\BannerController' );

     /**
    * Bloqueios Temporários
    */
    Route::resource( 'bloqueios', 'Admin\BloqueiosController' );

    /**
    * Descontos
    */
    Route::resource( 'descontos', 'Admin\DescontoController' );
    Route::post('descontos/{id}/active', ['uses' => 'Admin\DescontoController@active', 'as' => 'descontos.active']);

    /**
    * Cargos
    */
    Route::resource( 'cargos', 'Admin\CargoController' );
    Route::post('cargo/{id}/active', ['uses' => 'Admin\CargoController@active', 'as' => 'cargos.active']);
    Route::post('cargo/{id}/activecv', ['uses' => 'Admin\CargoController@activecv', 'as' => 'cargos.activecv']);


    /**
    * Concursos
    */
    Route::resource( 'concursos', 'Admin\ConcursoController' );
    Route::post('concurso/{id}/active', ['uses' => 'Admin\ConcursoController@active', 'as' => 'concurso.active']);


    /**
    * Categorias
    */
    Route::resource( 'categorias', 'Admin\CategoriaController' );

    /**
    * Curriculos
    */
    Route::resource( 'curriculos', 'Admin\CurriculoController' );



    /**
    * Empresas
    */
    Route::resource( 'empresas', 'Admin\EmpresaController' );

     /**
    * Estatísticas
    */
    Route::resource( 'estatisticas', 'Admin\EstatisticasController' );


    /**
    * Linguas
    */
    Route::resource( 'linguas', 'Admin\LinguaController' );



    /**
    * Parceiros
    */
    Route::resource( 'parceiros', 'Admin\ParceiroController' );
    Route::post('parceiro/{id}/active', ['uses' => 'Admin\ParceiroController@active', 'as' => 'parceiro.active']);

    /**
    * Ramos
    */
    Route::resource( 'ramos', 'Admin\RamoController' );

    /**
    * Temas
    */
    Route::resource( 'temas', 'Admin\TemaController' );

     /**
    * Testmail
    */
    Route::get('testmail', ['as' => 'testmail', 'uses' => 'TestmailController@create' ]);
    Route::post('testmail', ['as' => 'testmail.store', 'uses' => 'TestmailController@store' ]);

    /**
    * Vagas
    */
    Route::resource( 'vagas', 'Admin\VagaController' );
    Route::post('vaga/{id}/active', ['uses' => 'Admin\VagaController@active', 'as' => 'vagas.active']);
    Route::post('vaga/{id}/disable', ['uses' => 'Admin\VagaController@disable', 'as' => 'vagas.disable']);

     /**
    * Peritos
    */
    Route::resource( 'peritos', 'Admin\PeritoController' );
    Route::get('peritos/excel/{type}', 'Admin\PeritoController@excel');
    Route::get('peritos/downloadExcel/{type}', 'Admin\PeritoController@downloadExcel');
    

         /**
    * Usuários
    */
    Route::resource( 'usuarios', 'Admin\UsuarioController' );
    Route::get('usuarios/downloadExcel/{type}', 'Admin\UsuarioController@downloadExcel');
    Route::post('usuarios/{id}/active', ['uses' => 'Admin\UsuarioController@active', 'as' => 'usuarios.active']);





});

//
//Route::group([ 'as' => 'farmaceutico.', 'prefix' => 'farmaceutico',  'middleware' => ['auth', 'IsFarmaceutico']], function() {
//
//    /**
//    * Home
//    */
//    Route::get('/',['as' => 'home', function() {
//        return View::make('farmaceutico::home');
//    }]);
//
//});
//
//
//Route::group([ 'as' => 'empresa.', 'prefix' => 'empresa',  'middleware' => ['auth', 'IsEmpresa']], function() {
//
//    /**
//    * Home
//    */

app/Http/Controllers/Admin/ParceiroController.php
<?php

namespace App\Http\Controllers\Admin;

use File;
use App\Empresa;
use App\Parceiro;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Input;

class ParceiroController extends Controller {

    /**
    *
    * Mostrar Parceiros
    *
    **/
	public function index(Request $filters) {

        $parceiroSelected = \Request::get('parceiroSelected');
        $dataParceiro = \Request::get('dataParceiro');
        $modalidadeParceiro = \Request::get('modalidadeParceiro');
        $ativoParceiro = \Request::get('ativoParceiro');
        $parceiros = Parceiro::where('TT011CC001','like','%'.$parceiroSelected.'%')
          -> where('created_at','like','%'.$dataParceiro.'%')
          -> where(function($query)
                // Aqui coloquei pelo ID do tema, que deve ser identico e por isso utilizo o "=". Mas apenas executa a função se $temaArtigo não estiver vazia.
                            {
                                $ativoParceiro = \Request::get('ativoParceiro');
                                if (  $ativoParceiro != "" ){
                                    $query->   where('TT011CC005','=', $ativoParceiro );                                }
                            })
          -> where(function($query)
                // Aqui coloquei pelo ID do tema, que deve ser identico e por isso utilizo o "=". Mas apenas executa a função se $temaArtigo não estiver vazia.
                            {
                                $modalidadeParceiro = \Request::get('modalidadeParceiro');
                                if (  $modalidadeParceiro != "" ){
                                    $query->   where('TT011CC002','=', $modalidadeParceiro );
                                }
                            })
          -> orderBy ( 'TT011CC000', 'ASC' ) -> paginate ( 12 );

        // Request via Ajax?
        if ( $filters -> ajax() ) {
            return view( 'admin::parceiros.load', compact( 'parceiros', 'parceiroSelected', 'dataParceiro', 'modalidadeParceiro','ativoParceiro'));
        } else {
            return View ( 'admin::parceiros.index', compact([ 'parceiros' , 'parceiroSelected', 'dataParceiro', 'modalidadeParceiro', 'ativoParceiro']));
        }
	}


    /**
    *
    * Ativar Parceiro
    *
    **/
	public function active( $id ) {

        // Dados do Parceiro
        if ( $parceiro = Parceiro::find( $id )) {

            // Parceiro Habilitado?
            if ( $parceiro -> TT011CC005 ) {
                $msg = 'Parceiro desabilitado com sucesso';
                $parceiro -> TT011CC005 = false;
            } else {
                $msg = 'Parceiro habilitado com sucesso';
                $parceiro -> TT011CC005 = true;
            }

            $parceiro -> save();
//            return redirect() -> back() -> with( 'success', $msg );
            $urlFiltroAtual = \Request::get('urlFiltroAtual');
            $paginacaoAtual = \Request::get('paginacaoAtual');
            return redirect('admin/parceiros?page=' .  $paginacaoAtual . $urlFiltroAtual )-> with( 'success', $msg );
        }

        return redirect() -> back() -> with( 'alert', 'Parceiro não encontrado' );
	}


    /**
    *
    * Cadastrar Parceiros
    *
    **/
    public function create() {
        $empresas = Empresa::pluck( 'TT010CC005', 'TT010CC000' );
        return View ( 'admin::parceiros.create', compact( 'empresas' ));
    }

    /**
    *
    * Gravar Parceiro
    *
    **/
    public function store( Request $request ) {

        $this -> validate( $request, Parceiro::$rules, ['dimensions' => 'Dimensões 400 x 150'] );
        $parceiro = new Parceiro();
        $parceiro -> fill( $request -> all() );
        $parceiro -> save();

        //$parceiro -> TT011CC003 = 'img/parceiros/par-' . rand ( 111111, 999999 ) . '-' . $parceiro -> TT011CC000 . '.' . $request -> file( 'TT011CC003' ) -> getClientOriginalExtension();
        $parceiro -> TT011CC003 = 'img/parceiros/' . $request -> file( 'TT011CC003' ) -> getClientOriginalName();

        $request -> file( 'TT011CC003' ) -> move (
            base_path() . '/public/img/parceiros/', $parceiro -> TT011CC003
        );

        $parceiro -> save();

        return redirect() -> back() -> with( 'success', 'Parceiro cadastrado com sucesso' );
    }

    /**
    *
    * Editar Parceiros
    *
    **/
    public function edit( $id ) {
        $parceiro = Parceiro::find( $id );
        $empresas = Empresa::pluck( 'TT010CC005', 'TT010CC000' );
        return View ( 'admin::parceiros.edit', compact([ 'parceiro', 'empresas' ]));
    }

    /**
    *
    * Atualizar Parceiro
    *
    **/
    public function update( Request $request, $id ) {

        // Dados do Parceiro
        if ( $parceiro = Parceiro::find( $id )) {

            $this -> validate( $request, Parceiro::$updateRules, ['dimensions' => 'Dimensões 400 x 150'] );
            $validator = Validator::make(Input::all(), Parceiro::$imageRules);
            if ($validator->passes()){
                // Deletar imagem antiga
                if ( File::exists( $parceiro -> TT011CC003 )) {
                File::delete( $parceiro -> TT011CC003 );
            }}
            // Dados novos
            $parceiro -> fill( $request -> all() );
            //$parceiro -> TT011CC003 = 'img/parceiros/par-' . rand ( 111111, 999999 ) . '-' . $parceiro -> TT011CC000 . '.' . $request -> file( 'TT011CC003' ) -> getClientOriginalExtension();
            if ($validator->passes()){
                $parceiro -> TT011CC003 = 'img/parceiros/' . $request -> file( 'TT011CC003' ) -> getClientOriginalName();
                $request -> file( 'TT011CC003' ) -> move( base_path() . '/public/img/parceiros/', $parceiro -> TT011CC003 );
            }
            $parceiro -> save();
            return redirect() -> back() -> with( 'success', 'Parceiro atualizado com sucesso' );
        }

        return redirect() -> back() -> with( 'alert', 'Parceiro não encontrado' );
    }





    /**
    *
    * Deletar Parceiro
    *
    **/
    public function destroy( $id ) {

        if ( $parceiro = Parceiro::find( $id )) {

            if ( count( $parceiro -> descontos )) {
                return redirect() -> back() -> with( 'alert', 'Descontos relacionados com o Parceiro' );
            } elseif ( count( $parceiro -> banners )) {
                return redirect() -> back() -> with( 'alert', 'Banners relacionados com o Parceiro' );
            }

            $parceiro -> delete();

            return redirect() -> back() -> with( 'success', 'Parceiro deletado com sucesso' );
        }

        return redirect() -> back() -> with( 'alert', 'Parceiro não encontrado' );
    }
}

resources/views/admin/parceiros/create.blade.php
<!-- layout Master -->
@extends('admin::app')

<!-- Título -->
@section('titulo') Cadastro de Parceiros | Admin @stop

<!-- Conteúdo -->
@section('conteudo')

<!-- Título -->
<h2 class="m-3">Cadastro dos Parceiros</h2>
<!-- /Título -->

<!-- Mensagens de sucesso -->
@if ($message = Session::get('success'))
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <p class="mb-0">
        {{ $message }}
    </p>
</div>
@endif
<!-- /Mensagens de sucesso -->

<!-- Mensagens de erro -->
@if ( count( $errors ) > 0 )
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <p class="mb-0"> Confira os campos em destaque </p>
</div>
@endif
<!-- /Mensagens de erro -->

<div class="card my-std">
    <div class="card-block">
        <div class="title clearfix">
            <div class="title-form"><span class="cor-texto"> Parceiro </span></div>
        </div>

        {{ Form::open(['route' => 'admin.parceiros.store', 'method' => 'POST', 'files' => true ]) }}

        <div class="row">
            <!-- Nome -->
            <div class="col-12 col-sm-6">
                <div class="form-group @if ( $errors -> has( 'TT011CC001' )) has-danger @endif">
                    {{ Form::label( 'TT011CC001', 'Nome *', ['class' => 'form-control-label']) }}
                    {{ Form::text
                        (
                            'TT011CC001',
                            null,

                            [
                                'class' => 'form-control',
                                'maxlength' => '150'
                            ]
                        )
                    }}
                    <!-- Erro -->
                    @if ($errors->has('TT011CC001'))
                    <div class="form-control-feedback">
                        {{ $errors->first('TT011CC001') }}
                    </div>
                    @endif
                    <!-- /Erro -->
                </div>
            </div>
            <!-- /Nome -->

            <!-- Tipo -->
            <div class="col-12 col-sm-6">
                <div class="form-group @if ( $errors -> has( 'TT011CC002' )) has-danger @endif">
                    {{ Form::label('TT011CC002', 'Tipo de Parceria *', ['class' => 'form-control-label']) }}
                    {{ Form::select
                        (
                            'TT011CC002',

                            [
                                'BE' => 'PAF Empregos',
                                'CB' => 'PAF Descontos'
                            ],

                            null,

                            [
                                'class' => 'form-control',
                                'placeholder' => 'Selecione...'
                            ]
                        )
                    }}
                    <!-- Erro -->
                    @if ($errors->has('TT011CC002'))
                    <div class="form-control-feedback">
                        {{ $errors->first('TT011CC002') }}
                    </div>
                    @endif
                    <!-- /Erro -->
                </div>
            </div>
            <!-- /Tipo -->
        </div>

        <div class="row">

            <!-- Site -->
            <div class="col-12 col-md-6">
                <div class="form-group @if ( $errors -> has( 'TT011CC004' )) has-danger @endif">
                    {{ Form::label( 'TT011CC004', 'Site', ['class' => 'form-control-label' ]) }}
                    <!-- Input -->
                    {{ Form::text
                        (
                            'TT011CC004',
                            null,

                            [
                                'class' => 'form-control',
                                'maxlength' => '150',
                                'placeholder' => 'https://www.exemplo.com.br'
                            ]
                        )
                    }}
                    <!-- /Input -->

                    <!-- Erro -->
                    @if ($errors -> has( 'TT011CC004' ))
                    <div class="form-control-feedback">
                        {{ $errors->first('TT011CC004') }}
                    </div>
                    @endif
                    <!-- /Erro -->
                </div>
            </div>
            <!-- /Site -->

            <!-- Imagem -->
            <div class="col-12 col-md-6">
                <div class="form-group @if ( $errors -> has( 'TT011CC003' )) has-danger @endif">
                    {{ Form::label('TT011CC003', 'Imagem * (400px x 150px)', ['class' => 'form-control-label']) }}
                    <div class="input-group">
                        <label class="input-group-btn mb-0">
                            <span class="btn btn-secondary">
                                Upload <input name="TT011CC003" type="file" style="display: none;">
                            </span>
                        </label>
                        <input type="text" class="form-control" readonly>
                    </div>

                    <!-- Erro -->
                    @if ( $errors -> has( 'TT011CC003' ))
                    <div class="form-control-feedback">
                        {{ $errors->first( 'TT011CC003' ) }}
                    </div>
                    @endif
                    <!-- /Erro -->
                </div>
            </div>
            <!-- /Imagem -->
        </div>

        <div class="row mb-1">
            <div class="col-12">
                <p class="card-text text-uppercase"><strong>( * ) Campos obrigatórios</strong></p>
            </div>
        </div>

        <!-- Controle -->
        <div class="row">
            <div class="col-12 col-sm-3"></div>

            <!-- Voltar -->
            <div class="col-12 col-sm-3">
                <a class="btn btn-block btn-admin mb-1" href="{{ URL::Route( 'admin.parceiros.index' ) }}">
                    <i class="fa fa-arrow-left fa-2x" aria-hidden="true"></i>
                </a>
            </div>
            <!-- /Voltar -->

            <!-- Confirmar -->
            <div class="col-12 col-sm-3">
                {{ Form::button
                   (
                        '<i class="fa fa-check fa-2x" aria-hidden="true"></i>',

                        [
                            'class' => 'btn btn-block btn-admin',
                            'type' => 'submit'
                        ]
                    )
                }}
            </div>
            <!-- /Confirmar -->

            <div class="col-12 col-sm-3"></div>
        </div>
        <!-- /Controle -->
    </div>
    {{ Form::close() }}
</div>

@stop

resources/views/admin/parceiros/load.blade.php
<!-- Parceiros -->

<div class="row">
@foreach( $parceiros as $parceiro )
   <!--Aqui vai capturar a URL e enviar para o input urlFiltroAtual para que seja enviado ao controler e trazido como link da página-->
<script type="text/javascript">
       var filtro = window.location.href;

       if (filtro.includes("parceiroSelected="))
       {
           var urlFiltro = window.location.href;
           urlFiltro = urlFiltro.replace("http://pafnovo.crfsp.org.br/admin/parceiros?","");
           for(i=0;i<document.getElementsByName("urlFiltroAtual").length;i++){

               document.getElementsByName("urlFiltroAtual")[i].value = '&'+urlFiltro;
           }
       }
       else{
           document.getElementsByName("urlFiltroAtual").value = "";
       }
</script>
<!--FIM do script de capturar URL-->
    <div class="col-12 col-lg-4">
        <div class="card parceiro my-std">
            <div class="card-block text-center text-lg-left">
                <div class="row cor-texto">
                    <div class="col-12 col-lg-4">

                        <figure class="figure mb-1">
                            {{ Html::image( $parceiro -> TT011CC003, $parceiro -> TT011CC001, array( 'class' => 'img-fluid' )) }}
                        </figure>
                    </div>
                         <!-- Ativar Parceiro -->
                        <div class="col-12 col-lg-8"> {{ Form::open([ 'method' => 'Post','route' => [ 'admin.parceiro.active', $parceiro-> TT011CC000 ]]) }}
                         <input type="hidden" class="form-control" name="paginacaoAtual" value="{{ $parceiros->currentPage() }}" >
                         <input type="hidden" class="form-control" name="urlFiltroAtual" value="" >
                        <label class="switch float-right">
                         {{ Form::checkbox('TT011CC005', $parceiro -> TT011CC005, $parceiro -> TT011CC005, ['onChange' => 'this.form.submit()']) }}
                            <div class="slider slider-BE round"></div>
                        </label>
                        {{ Form::close() }}
                           <!-- /Ativar Parceiro  -->
                        <h5 class="media-heading">
                            {{ $parceiro -> TT011CC001 }}
                        </h5>

                        <!-- Tipo -->
                        <p>
                           <strong class="text-uppercase">
                                @if  ( $parceiro -> TT011CC002 == 'CB' )
                                    Clube de Descontos
                                @else
                                    Bolsa de Emprego
                                @endif
                            </strong>
                        </p>
                        <!-- /Tipo -->
                    </div>
                </div>

                <hr>

                <!-- Controle -->
                <div class="row">
                    <div class="col-12 col-sm-3"></div>

                    <!-- Editar -->
                    <div class="col-12 col-sm-3">
                        <a class="btn btn-block btn-admin mb-2 mb-md-0" href="{{ route( 'admin.parceiros.edit', $parceiro -> TT011CC000 )}}">
                            <i class="fa fa-pencil-square-o fa-2x" aria-hidden="true"></i>
                        </a>
                    </div>
                    <!-- Editar -->

                    <!-- Deletar -->
                    <div class="col-12 col-sm-3">
                        {{ Form::open([ 'method' => 'Delete','route' => [ 'admin.parceiros.destroy', $parceiro -> TT011CC000 ]]) }}
                        {{ Form::button
                            (
                                '<i class="fa fa-trash-o fa-2x" aria-hidden="true"></i>',

                                [
                                    'class' => 'btn btn-block btn-admin',
                                    'type' => 'submit'
                                ]
                            )
                        }}
                        {{ Form::close() }}
                    </div>
                    <!-- Deletar -->

                    <div class="col-12 col-sm-3"></div>
                </div>
                <!-- /Controle -->
            </div>
        </div>
    </div>
@endforeach
</div>
<!-- /Parceiros -->

<!-- Paginação -->
{{ $parceiros -> links( 'partials.pagination' ) }}