routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
Route::resource('demo', 'DemoController');
/**
 * Home
 */
Route::get( '/', 'HomeController@index' ); /* aqui poderia ser uma função - Route::get( '/',  function () { return view ('texto'); });  com texto ao invés de chamar um controller. */

/**
 * Sobre
 */
Route::get( 'sobre', 'PagesController@sobre' );

/**
 * Artigos
 */
Route::resource( 'artigos', 'ArtigoController', ['only' => ['index', 'show']]);

/***********************************************************
 * -------------------------------------------------------------------------
 *  PAF-Regional
 * -------------------------------------------------------------------------
 */

/**
 * Seccionais
 */
Route::get( 'seccionais/{id?}', ['uses' => 'PagesController@seccional', 'as' => 'seccionais.index']);


/***********************************************************
 * -------------------------------------------------------------------------
 *  PAF-Empregos
 * -------------------------------------------------------------------------
 */

/**
 * Vagas
 */
Route::resource( 'vagas', 'VagaController' );
Route::resource( 'totalvagas', 'VagaController@totalvagas' );
Route::get( 'estagios/create', ['uses' => 'VagaController@estagio', 'as' => 'estagios']);


/**
 * Peritos cadastro
 */

Route::get('perito', ['as' => 'perito', 'uses' => 'PeritoController@create' ]);
Route::post('perito', ['as' => 'perito.store', 'uses' => 'PeritoController@store' ]);




/**
 * Concursos
 */
Route::resource('concursos', 'ConcursoController');
/**
 * Logout
 */
Route::get('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);

/**
 * Currículos
 */

Route::group( ['as' => 'curriculos.', 'prefix' => 'curriculos', 'middleware' => ['auth']], function() {



    /**
     * Home
     */
    Route::get('/',['as' => 'home', function() {
        return View::make('site::Curriculos.home');
    }]);

    /**
     * Curriculos/Farmaceuticos com login
     */
    Route::group( [ 'as' => 'farmaceuticos.', 'prefix' => 'farmaceuticos',  'middleware' => 'IsFarmaceutico'], function() {

        /**
         * Currículo
         */
        Route::resource( 'curriculo', 'Curriculos\CurriculoController', ['except' => [ 'destroy' ]]);
        Route::resource( 'formacao', 'Curriculos\Farmaceuticos\FormacaoController');
        Route::post('formacao/update', ['uses' => 'Curriculos\Farmaceuticos\FormacaoController@update']);
        Route::resource( 'deficiencia', 'Curriculos\Farmaceuticos\DeficienciaController');
        Route::post('deficiencia/update', ['uses' => 'Curriculos\Farmaceuticos\DeficienciaController@update']);
        Route::resource( 'extracurso', 'Curriculos\Farmaceuticos\ExtracursoController');
        Route::post('extracurso/update', ['uses' => 'Curriculos\Farmaceuticos\ExtracursoController@update']);
        Route::resource( 'idioma', 'Curriculos\Farmaceuticos\IdiomaController');
        Route::post('idioma/update', ['uses' => 'Curriculos\Farmaceuticos\IdiomaController@update']);
        Route::resource( 'interesse', 'Curriculos\Farmaceuticos\InteresseController');
        Route::post('interesse/update', ['uses' => 'Curriculos\Farmaceuticos\InteresseController@update']);
        Route::resource( 'experiencia', 'Curriculos\Farmaceuticos\ExperienciaController');
        Route::post('experiencia/update', ['uses' => 'Curriculos\Farmaceuticos\ExperienciaController@update']);
        Route::get( 'meusdados', ['uses' => 'Curriculos\Farmaceuticos\CurriculoController@perfilfarmaceutico', 'as' => 'Curriculo.perfilfarmaceutico']);


    });

    /**
     * Curriculos/Empresas  com login
     */
    Route::group( [ 'as' => 'empresas.', 'prefix' => 'empresas', 'middleware' => 'IsEmpresa'], function() {

        /**
         * Home
         */
        Route::get('/',['as' => 'home', function() {
            return View::make('site::Curriculos.empresas.home');
        }]);
        Route::resource( 'empresa', 'Curriculos\Empresas\EmpresaController');
        Route::post('empresa/update', ['uses' => 'Curriculos\Empresas\EmpresaController@update']);
        Route::post('empresa/{id}/disable', ['uses' => 'Curriculos\Empresas\EmpresaController@disable', 'as' => 'empresa.disable']);

        Route::resource( 'vaga', 'Curriculos\Empresas\VagaController');
        Route::post('vaga/update', ['uses' => 'Curriculos\Empresas\VagaController@update']);
        Route::resource( 'pesquisa', 'Curriculos\Empresas\PesquisacvController');
        Route::post('pesquisa/update', ['uses' => 'Curriculos\Empresas\PesquisacvController@update']);
        Route::resource( 'estatisticavagas', 'Curriculos\Empresas\EstatisticavagasController');
        Route::post('desabilitarvaga/{id}/active', ['uses' => 'Curriculos\Empresas\EstatisticavagasController@disable', 'as' => 'estatisticavagas.disable']);


        /**
        * Sobre
        */
        Route::get( 'sobre', 'PagesController@sobre' );
        });
        });






/***********************************************************
 * -------------------------------------------------------------------------
 *  PAF-Descontos
 * -------------------------------------------------------------------------
 */

/**
 * Descontos
 */
Route::resource('descontos', 'DescontoController');
Route::get( 'empresas', ['uses' => 'DescontoController@empresa', 'as' => 'empresa']);

 /**
  * Usuario Inativo
  */
    Route::get( 'usuarioinativo', 'PagesController@usuarioinativo' );


 /***********************************************************
 * -------------------------------------------------------------------------
 *  Envio de Contatos
 * -------------------------------------------------------------------------
 */
Route::get('contato', ['as' => 'contato', 'uses' => 'ContatoController@create' ]);
Route::get( 'contato/serparceiro', ['uses' => 'ContatoController@serparceiro', 'as' => 'serparceiro']);
Route::get( 'contato/indicarparceiro', ['uses' => 'ContatoController@indicarparceiro', 'as' => 'indicarparceiro']);
Route::get( 'contato/retiraranuncio', ['uses' => 'ContatoController@retiraranuncio', 'as' => 'retiraranuncio']);
Route::post('contato', ['as' => 'contato.store', 'uses' => 'ContatoController@store' ]);

/***********************************************************
 * -------------------------------------------------------------------------
 *  Cidades do Brasil
 * -------------------------------------------------------------------------
 */
Route::get( '/ufs/', function( $uf = null ) {
    return response() -> json( App\Cidade::select( 'TT008CC001' ) -> distinct('TT008CC001') -> orderBy('TT008CC001') -> get());
});

Route::get( '/cidades/{uf}', function( $uf = null ) {
    return response() -> json( App\Cidade::where( 'TT008CC001', $uf ) -> orderBy('TT008CC003') -> get());
});

/**
 * Teste Email
 */
Route::get( 'email', 'PagesController@email' );



//TESTES DE LOGIN E PERFIL////////////////////////////////////////////////////////////


Route::get( '/teste', function () {

 $user = Auth::user();

    if($user->isAdmin()){
        echo "Logado como Admin";

    }
    if($user->isFarmaceutico()){
        echo "Logado como Farmaceutico";

    }
    if($user->isEmpresa()){
        echo "Logado como Empresa";

    }

});

/***********************************************************
 * -------------------------------------------------------------------------
 *  Cadastro de Farmaceuticos
 * -------------------------------------------------------------------------
 */ 

        /**
         * Digitar o CPF
         */
Route::resource( 'cadastro', 'Soap\SoapController' );
Route::post('inserirCRF', 'Soap\SoapController@buscasoap')->name('cadastro.buscasoap');
Route::post('inserirEmail', 'Soap\SoapController@validacrf')->name('cadastro.validacrf');
Route::get('pfs', 'Soap\SoapController@pfs');
Route::post('enviaemail', ['as' => 'cadastro.enviaemail', 'uses' => 'Soap\SoapController@enviaemail' ]);
//Route::get( 'enviaemail', 'Soap\SoapController@enviaemail')->name('cadastro.enviaemail');


//Route::get( 'admin2/user/roles', ['middleware'=> ['web'], function () {
//
//    return "Middleware role";
//}  ]);

Route::get( '/admin2', 'AdminController@index');

//TESTES DE LOGIN E PERFIL////////////////////////////////////////////////////////////


/***********************************************************
 * -------------------------------------------------------------------------
 *  Painel Administrador
 * -------------------------------------------------------------------------
 */
Route::group([ 'as' => 'admin.', 'prefix' => 'admin',  'middleware' => ['auth', 'IsAdmin']], function() {

    /**
    * Home
    */
    Route::get('/',['as' => 'home', function() {
        return View::make('admin::home');
    }]);

    /**
    * Artigos
    */
    Route::resource( 'artigos', 'Admin\ArtigoController' );
    Route::post('artigo/{id}/active', ['uses' => 'Admin\ArtigoController@active', 'as' => 'artigos.active']);

    /**
    * Banners
    */
    Route::resource( 'banners', 'Admin\BannerController' );

     /**
    * Bloqueios Temporários
    */
    Route::resource( 'bloqueios', 'Admin\BloqueiosController' );

    /**
    * Descontos
    */
    Route::resource( 'descontos', 'Admin\DescontoController' );
    Route::post('descontos/{id}/active', ['uses' => 'Admin\DescontoController@active', 'as' => 'descontos.active']);

    /**
    * Cargos
    */
    Route::resource( 'cargos', 'Admin\CargoController' );
    Route::post('cargo/{id}/active', ['uses' => 'Admin\CargoController@active', 'as' => 'cargos.active']);

app/Http/Controllers/Admin/ArtigoController.php
<?php

namespace App\Http\Controllers\Admin;

use DB;
use File;
use App\Tema;
use App\Artigo;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Search\Artigo\ArtigoSearch;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Input;

class ArtigoController extends Controller {

    /**
    *
    * Mostrar Artigos
    *
    **/
	public function index(Request $filters) {


        $temas = Artigo::select( DB::raw('TT004CC000, TT004CC002'))
                -> join('TT004', 'TT009.TT009CC001', '=', 'TT004.TT004CC000')
                -> groupBy('TT004CC000', 'TT004CC002')
                -> orderBy('TT004CC002')
                -> get();


        $tituloArtigo = \Request::get('tituloArtigo');
        $dataArtigo = \Request::get('dataArtigo');
        $temaArtigo = \Request::get('temaArtigo');
        $artigos = Artigo::where(function($query)
                // Aqui coloquei pelo ID do tema, que deve ser identico e por isso utilizo o "=". Mas apenas executa a função se $temaArtigo não estiver vazia.
                            {
                                $temaArtigo = \Request::get('temaArtigo');
                                if (  $temaArtigo != "" ){
                                    $query->  where('TT009CC001','=', $temaArtigo );

                                }
                            })
            -> where('TT009CC002','like','%'.$tituloArtigo.'%')
              -> where('created_at','like','%'.$dataArtigo.'%')

            ->orderBy ( 'created_at', 'DESC' ) -> paginate ( 6 );

        // Request via Ajax?
        if ( $filters -> ajax() ) {
            return view( 'admin::artigos.load', compact( 'artigos', 'temas', 'tituloArtigo', 'dataArtigo', 'temaArtigo' ));
        } else {
            return View ( 'admin::artigos.index', compact([ 'artigos', 'temas', 'tituloArtigo', 'dataArtigo', 'temaArtigo' ]));
        }
	}

    /**
    *
    * Mostrar Artigo
    *
    **/
	public function show( $id ) {
        $artigo = Artigo::find( $id );
        return View ( 'admin::artigos.show', compact([ 'artigo' ]));
	}

    /**
    *
    * Ativar Artigo
    *
    **/
	public function active( $id ) {

        // Dados do Artigo
        if ( $artigo = Artigo::find( $id )) {

            // Artigo Habilitado?
            if ( $artigo -> TT009CC005 ) {
                $msg = 'Artigo desabilitado com sucesso';
                $artigo -> TT009CC005 = false;
            } else {
                $msg = 'Artigo habilitado com sucesso';
                $artigo -> TT009CC005 = true;
            }

            $artigo -> save();
//            return redirect() -> back() -> with( 'success', $msg );
            $urlFiltroAtual = \Request::get('urlFiltroAtual');
            $paginacaoAtual = \Request::get('paginacaoAtual');
            return redirect('admin/artigos?page=' .  $paginacaoAtual . $urlFiltroAtual )-> with( 'success', $msg );
        }

        return redirect() -> back() -> with( 'alert', 'Artigo não encontrada' );
	}

    /**
    *
    * Cadastrar Artigos
    *
    **/
    public function create() {
        $temas = Tema::pluck('TT004CC002', 'TT004CC000');
        return View ( 'admin::artigos.create', compact( 'temas' ));
    }

    /**
    *
    * Gravar Artigo
    *
    **/
    public function store( Request $request ) {

        $this -> validate( $request, Artigo::$rules, ['dimensions' => 'Dimensões 380 x 280'] );

        // Dados do Artigo
        $artigo = new Artigo();
        $artigo -> fill( $request -> all() );
        $artigo -> save();

        //$artigo -> TT009CC003 = 'img/artigos/art-' . rand ( 111111, 999999 ) . '-' . $artigo -> TT009CC000 . '.' . $request -> file( 'TT009CC003' ) -> getClientOriginalExtension();
        $artigo -> TT009CC003 = 'img/artigos/' . $request -> file( 'TT009CC003' ) -> getClientOriginalName();

        $request -> file( 'TT009CC003' ) -> move (

            base_path() . '/public/img/artigos/', $artigo -> TT009CC003

        );

        $artigo -> save();

        return redirect() -> back() -> with( 'success', 'Artigo cadastrado com sucesso' );
    }

    /**
    *
    * Editar Artigos
    *
    **/
    public function edit( $id ) {
        $artigo = Artigo::find( $id );
        $temas = Tema::pluck('TT004CC002', 'TT004CC000');
        return View ( 'admin::artigos.edit', compact([ 'artigo', 'temas' ]));
    }

    /**
    *
    * Atualizar Artigo
    *
    **/
    public function update( Request $request, $id ) {
        $this -> validate( $request, Artigo::$updateRules, ['dimensions' => 'Dimensões 380 x 280'] );
        // Dados do Artigo
        if ( $artigo = Artigo::find( $id )) {
            // Dados novos

            $validator = Validator::make(Input::all(), Artigo::$imageRules);
            if ($validator->passes()){
                // Deletar imagem antiga
                if ( File::exists( $artigo -> TT009CC003 )) {
                File::delete( $artigo -> TT009CC003 );
                }

            }
             $artigo -> fill( $request -> all() );
            //$artigo -> TT009CC003 = 'img/artigos/art-' . rand ( 111111, 999999 ) . '-' . $artigo -> TT009CC000 . '.' . $request -> file( 'TT009CC003' ) -> getClientOriginalExtension();

            if ($validator->passes()){
                $artigo -> TT009CC003 = 'img/artigos/' . $request -> file( 'TT009CC003' ) -> getClientOriginalName();
            $request -> file( 'TT009CC003' ) -> move ( base_path() . '/public/img/artigos/', $artigo -> TT009CC003 );
            }

            $artigo -> save();
            return redirect() -> back() -> with( 'success', 'Artigo atualizado com sucesso' );
        }
        return redirect() -> back() -> with( 'alert', 'Artigo não encontrado' );
    }

    /**
    *
    * Deletar Artigo
    *
    **/
    public function destroy( $id ) {

        if ( $artigo = Artigo::find( $id )) {

            $artigo -> delete();

            if ( File::exists( $artigo -> TT009CC003 )) {
                File::delete( $artigo -> TT009CC003 );
            }

            return redirect() -> route( 'admin.artigos.index' ) -> with( 'success', 'Artigo deletado com sucesso' );
        }

        return redirect() -> back() -> with( 'alert', 'Artigo não encontrado' );
    }
}

app/Http/Controllers/ArtigoController.php
<?php

namespace App\Http\Controllers;

use App\Tema;
use App\Artigo;
use Illuminate\Http\Request;
use App\Search\Artigo\ArtigoSearch;

class ArtigoController extends Controller {

    /**
    *
    * Carregar página de Artigos
    *
    **/
	public function index( Request $filters ) {

        $artigos = ArtigoSearch::apply( $filters );

        // Request via Ajax?
        if ( $filters -> ajax() ) {
            return view( 'site::Artigos.load', compact( 'artigos' ));
        } else {
            $temas = Tema::orderBy( 'TT004CC002', 'DESC' ) -> get();
            return view( 'site::Artigos.index', compact( 'artigos', 'temas' ));
        }
	}

    /**
    * Mostrar página do Artigo
    *
    * @param  int  $id
    * @return View artigos.show
    */
    public function show( $id ) {

        if ( $artigo = Artigo::where( 'TT009CC005', true ) -> find( $id )) {

            $artigos = Artigo::where( 'TT009CC005', true ) -> orderBy( 'created_at', 'desc' ) -> limit( 6 ) -> get();
            return view ( 'site::Artigos.show', compact( 'artigo', 'artigos' ));
        }
        return redirect() -> back();
    }
}

resources/views/admin/artigos/index.blade.php
<!-- layout Master -->
@extends('admin::app')

<!-- Título -->
@section('titulo') Artigos | Admin @stop

<!-- Conteúdo -->
@section('conteudo')

<!-- Novo -->
        <div class="float-left">
            <a class="btn btn-admin" href="{{ URL::Route( 'admin.artigos.create' ) }}">
                <i class="fa fa-plus fa-2x" aria-hidden="true"></i>
            </a>
        </div>
 <!-- /Novo -->

<!-- Título -->
<h1 class="text-center">Artigos</h1>



<!-- Mensagens de sucesso -->
@if ( $message = Session::get( 'success' ))
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <p class="mb-0">
        {{ $message }}
    </p>
</div>
@endif
<!-- /Mensagens de sucesso -->

<!-- Alertas -->
@if ( $message = Session::get( 'alert' ))
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <p class="mb-0">{{ $message }}</p>
</div>
@endif
<!-- /Alertas -->



<!-- Buscas -->
<div class="card mb-3">
    <div class="card-block">

              <div class="row">
            <!-- Tipo de Vaga -->
            <div class="col-12 col-md-12">




{!! Form::open(['method'=>'GET','url'=>'admin/artigos','class'=>'filter-form navbar-left','role'=>'search'])  !!}

<div class="col-12 col-md-12">
<div class="row">
      <div class="col-12 col-md-2"> Tema
       <select class="form-control" name="temaArtigo">
               <option value="">Todos</option>
           @foreach( $temas as $tema )
                <option value="{{ $tema -> TT004CC000 }}"  @if ($tema -> TT004CC000 == $temaArtigo) selected @endif>{{ $tema -> TT004CC002 }}  </option>
           @endforeach
       </select>
    </div>
    <div class="col-12 col-md-4">Título <input type="text" class="form-control" name="tituloArtigo" value="{{$tituloArtigo}}" placeholder="..."></div>
    <div class="col-12 col-md-2 ">Data de criação<input type="date" class="form-control" name="dataArtigo" value="{{$dataArtigo}}" placeholder="..."></div>


   <div class="col-12 col-md-1"><br>
   <span class="input-group-btn ">
        <button class="btn btn-block btn-admin mb-1" type="submit">
            <i class="fa fa-search fa-2x"></i>
        </button>
    </span>
    </div>
    <div class="col-12 col-md-1"><br>
        <a href="/admin/artigos"> <i class="btn btn-block btn-admin mb-1 fa fa-eraser fa-2x"></i></a>
    </div>
</div>
{!! Form::close() !!}
  </div>

            </div>
        </div>
    </div>
</div>

  <!-- Buscas -->


<!-- Artigos -->
<section class="load-ajax">
    @include('admin::artigos.load')
</section>
<!-- /Artigos -->

@stop

resources/views/admin/artigos/load.blade.php
<!-- Artigos -->
<div class="row"> @foreach( $artigos as $artigo )
   <!--Aqui vai capturar a URL e enviar para o input urlFiltroAtual para que seja enviado ao controler e trazido como link da página-->
<script type="text/javascript">
       var filtro = window.location.href;

       if (filtro.includes("temaArtigo="))
       {
           var urlFiltro = window.location.href;
           urlFiltro = urlFiltro.replace("http://pafnovo.crfsp.org.br/admin/artigos?","");
           for(i=0;i<document.getElementsByName("urlFiltroAtual").length;i++){

               document.getElementsByName("urlFiltroAtual")[i].value = '&'+urlFiltro;
           }
       }
       else{
           document.getElementsByName("urlFiltroAtual").value = "";
       }
</script>
<!--FIM do script de capturar URL-->
    <div class="col-4">
        <div class="card my-std">
            <div class="card-block text-left">


                <div class="row">

                    <div class="col-12 col-md-4">
                      <!-- Ativar Artigo -->
                       {{ Form::open([ 'method' => 'Post','route' => [ 'admin.artigos.active', $artigo -> TT009CC000 ]]) }}
                        <input type="hidden" class="form-control" name="paginacaoAtual" value="{{ $artigos->currentPage() }}" >
                         <input type="hidden" class="form-control" name="urlFiltroAtual" value="" >
                        <label class="switch float-left"> {{ Form::checkbox('TT009CC005', $artigo -> TT009CC005, $artigo -> TT009CC005, ['onChange' => 'this.form.submit()']) }}
                            <div class="slider slider-artigo round"></div>
                        </label> {{ Form::close() }}
                        <!-- Ativar Artigo -->
                        <br>
                        <figure class="figure mb-1"> {{ Html::image( $artigo -> TT009CC003, $artigo -> TT009CC002, array( 'class' => 'img-fluid' )) }} </figure>
                    </div>
                    <div class="col-12 col-md-8">
                        <h5 class="media-heading text-md-left">
                            {{ $artigo -> TT009CC002 }}
                        </h5>
<!--                         {!! limitText( $artigo -> TT009CC004, 120 ) !!} -->
                         </div>
                </div>
                <hr>
                <!-- Controle -->
                <div class="row">
                    <!-- Visualizar -->
                    <div class="col-12 col-sm-4">
                        <a class="btn btn-block btn-admin mb-2 mb-md-0" href="{{ route( 'admin.artigos.show', $artigo -> TT009CC000 )}}"> <i class="fa fa-expand fa-2x" aria-hidden="true"></i> </a>
                    </div>
                    <!-- Visualizar -->
                    <!-- Editar -->
                    <div class="col-12 col-sm-4">
                        <a class="btn btn-block btn-admin mb-2 mb-md-0" href="{{ route( 'admin.artigos.edit', $artigo -> TT009CC000 )}}"> <i class="fa fa-pencil-square-o fa-2x" aria-hidden="true"></i> </a>
                    </div>
                    <!-- Editar -->
                    <!-- Deletar -->
                    <div class="col-12 col-sm-4"> {{ Form::open([ 'method' => 'Delete','route' => [ 'admin.artigos.destroy', $artigo -> TT009CC000 ]]) }} {{ Form::button ( '<i class="fa fa-trash-o fa-2x" aria-hidden="true"></i>', [ 'class' => 'btn btn-block btn-admin', 'type' => 'submit' ] ) }} {{ Form::close() }} </div>
                    <!-- Deletar -->
                </div>
                <!-- /Controle -->
            </div>
        </div>
    </div> @endforeach </div>
<!-- /Artigos -->
<!-- Paginação -->{{ $artigos -> links( 'partials.pagination' ) }}

resources/views/admin/artigos/show.blade.php
<!-- layout Master -->
@extends('admin::app')

<!-- Título -->
@section('titulo') Prévia dos Artigos | Admin @stop

<!-- Conteúdo -->
@section('conteudo')

<!-- Título -->
<h2 class="m-3">Prévia</h2>
<!-- /Título -->

<!-- Mensagens de sucesso -->
@if ( $message = Session::get( 'success' ))
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <p class="mb-0">
        {{ $message }}
    </p>
</div>
@endif
<!-- /Mensagens de sucesso -->

<!-- Alertas -->
@if ( $message = Session::get( 'alert' ))
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <p class="mb-0">{{ $message }}</p>
</div>
@endif
<!-- /Alertas -->

<div class="row">
    <div class="col-12">
        <div class="card my-std">
            <div class="card-block">

                <!-- Ativar Artigo -->
                {{ Form::open([ 'method' => 'Post','route' => [ 'admin.artigos.active', $artigo -> TT009CC000 ]]) }}
                <label class="switch float-right">
                    {{ Form::checkbox('TT009CC005', $artigo -> TT009CC005, $artigo -> TT009CC005, ['onChange' => 'this.form.submit()']) }}
                    <div class="slider slider-artigo round"></div>
                </label>
                {{ Form::close() }}
                <!-- /Ativar Artigo -->

                <!-- Title Artigos -->
                <div class="title clearfix">
                    <div class="title-form">
                        <span class="cor-artigos"> Prévia do Artigo </span>
                    </div>
                </div>
                <!-- /Title Artigos -->

                <h1 class="text-center">{{ $artigo -> TT009CC002 }}</h1>

                <figure class="figure artigo-img text-center">
                    {{ Html::image( $artigo -> TT009CC003, $artigo -> TT009CC002, array('class' => 'figure-img img-fluid img-thumbnail')) }}
                </figure>

                {!! $artigo -> TT009CC004 !!}

                <hr>

                <!-- Controle -->
                <div class="row">
                    <!-- Voltar -->
                    <div class="col-12 col-sm-3">
                        <a class="btn btn-block btn-admin mb-2 mb-md-0" href="{{ URL::previous() }}">
                            <i class="fa fa-arrow-left fa-2x" aria-hidden="true"></i>
                        </a>
                    </div>
                    <!-- /Voltar -->

                    <!-- Novo -->
                    <div class="col-12 col-sm-3">
                        <a class="btn btn-block btn-admin mb-2 mb-md-0" href="{{ URL::Route( 'admin.artigos.create' ) }}">
                            <i class="fa fa-plus fa-2x" aria-hidden="true"></i>
                        </a>
                    </div>
                    <!-- /Novo -->

                    <!-- Editar -->
                    <div class="col-12 col-sm-3">
                        <a class="btn btn-block btn-admin mb-2 mb-md-0" href="{{ route( 'admin.artigos.edit', $artigo -> TT009CC000 )}}">
                            <i class="fa fa-pencil-square-o fa-2x" aria-hidden="true"></i>
                        </a>
                    </div>
                    <!-- Editar -->

                    <!-- Deletar -->
                    <div class="col-12 col-sm-3">
                        {{ Form::open([ 'method' => 'Delete','route' => [ 'admin.artigos.destroy', $artigo -> TT009CC000 ]]) }}
                        {{ Form::button
                            (
                                '<i class="fa fa-trash-o fa-2x" aria-hidden="true"></i>',

                                [
                                    'class' => 'btn btn-block btn-admin',
                                    'type' => 'submit'
                                ]
                            )
                        }}
                        {{ Form::close() }}
                    </div>
                    <!-- Deletar -->
                </div>
                <!-- /Controle -->
            </div>
        </div>
    </div>
</div>

@stop