routes/web.php
        Route::post('formacao/update', ['uses' => 'Curriculos\Farmaceuticos\FormacaoController@update']);
        Route::resource( 'deficiencia', 'Curriculos\Farmaceuticos\DeficienciaController');
        Route::post('deficiencia/update', ['uses' => 'Curriculos\Farmaceuticos\DeficienciaController@update']);
        Route::resource( 'extracurso', 'Curriculos\Farmaceuticos\ExtracursoController');
        Route::post('extracurso/update', ['uses' => 'Curriculos\Farmaceuticos\ExtracursoController@update']);
        Route::resource( 'idioma', 'Curriculos\Farmaceuticos\IdiomaController');
        Route::post('idioma/update', ['uses' => 'Curriculos\Farmaceuticos\IdiomaController@update']);
        Route::resource( 'interesse', 'Curriculos\Farmaceuticos\InteresseController');
        Route::post('interesse/update', ['uses' => 'Curriculos\Farmaceuticos\InteresseController@update']);
        Route::resource( 'experiencia', 'Curriculos\Farmaceuticos\ExperienciaController');
        Route::post('experiencia/update', ['uses' => 'Curriculos\Farmaceuticos\ExperienciaController@update']);
        Route::get( 'meusdados', ['uses' => 'Curriculos\Farmaceuticos\CurriculoController@perfilfarmaceutico', 'as' => 'Curriculo.perfilfarmaceutico']);


    });

    /**
     * Curriculos/Empresas  com login
     */
    Route::group( [ 'as' => 'empresas.', 'prefix' => 'empresas', 'middleware' => 'IsEmpresa'], function() {

        /**
         * Home
         */
        Route::get('/',['as' => 'home', function() {
            return View::make('site::Curriculos.empresas.home');
        }]);
        Route::resource( 'empresa', 'Curriculos\Empresas\EmpresaController');
        Route::post('empresa/update', ['uses' => 'Curriculos\Empresas\EmpresaController@update']);
        Route::post('empresa/{id}/disable', ['uses' => 'Curriculos\Empresas\EmpresaController@disable', 'as' => 'empresa.disable']);

        Route::resource( 'vaga', 'Curriculos\Empresas\VagaController');
        Route::post('vaga/update', ['uses' => 'Curriculos\Empresas\VagaController@update']);
        Route::resource( 'pesquisa', 'Curriculos\Empresas\PesquisacvController');
        Route::post('pesquisa/update', ['uses' => 'Curriculos\Empresas\PesquisacvController@update']);
        Route::resource( 'estatisticavagas', 'Curriculos\Empresas\EstatisticavagasController');
        Route::post('desabilitarvaga/{id}/active', ['uses' => 'Curriculos\Empresas\EstatisticavagasController@disable', 'as' => 'estatisticavagas.disable']);


        /**
        * Sobre
        */
        Route::get( 'sobre', 'PagesController@sobre' );
        });
        });






/***********************************************************
 * -------------------------------------------------------------------------
 *  PAF-Descontos
 * -------------------------------------------------------------------------
 */

/**
 * Descontos
 */
Route::resource('descontos', 'DescontoController');
Route::get( 'empresas', ['uses' => 'DescontoController@empresa', 'as' => 'empresa']);

 /**
  * Usuario Inativo
  */
    Route::get( 'usuarioinativo', 'PagesController@usuarioinativo' );


 /***********************************************************
 * -------------------------------------------------------------------------
 *  Envio de Contatos
 * -------------------------------------------------------------------------
 */
Route::get('contato', ['as' => 'contato', 'uses' => 'ContatoController@create' ]);
Route::get( 'contato/serparceiro', ['uses' => 'ContatoController@serparceiro', 'as' => 'serparceiro']);
Route::get( 'contato/indicarparceiro', ['uses' => 'ContatoController@indicarparceiro', 'as' => 'indicarparceiro']);
Route::get( 'contato/retiraranuncio', ['uses' => 'ContatoController@retiraranuncio', 'as' => 'retiraranuncio']);
Route::post('contato', ['as' => 'contato.store', 'uses' => 'ContatoController@store' ]);

/***********************************************************
 * -------------------------------------------------------------------------
 *  Cidades do Brasil
 * -------------------------------------------------------------------------
 */
Route::get( '/ufs/', function( $uf = null ) {
    return response() -> json( App\Cidade::select( 'TT008CC001' ) -> distinct('TT008CC001') -> orderBy('TT008CC001') -> get());
});

Route::get( '/cidades/{uf}', function( $uf = null ) {
    return response() -> json( App\Cidade::where( 'TT008CC001', $uf ) -> orderBy('TT008CC003') -> get());
});

/**
 * Teste Email
 */
Route::get( 'email', 'PagesController@email' );



//TESTES DE LOGIN E PERFIL////////////////////////////////////////////////////////////


Route::get( '/teste', function () {

 $user = Auth::user();

    if($user->isAdmin()){
        echo "Logado como Admin";

    }
    if($user->isFarmaceutico()){
        echo "Logado como Farmaceutico";

    }
    if($user->isEmpresa()){
        echo "Logado como Empresa";

    }

});

/***********************************************************
 * -------------------------------------------------------------------------
 *  Cadastro de Farmaceuticos
 * -------------------------------------------------------------------------
 */ 

        /**
         * Digitar o CPF
         */
Route::resource( 'cadastro', 'Soap\SoapController' );
Route::post('inserirCRF', 'Soap\SoapController@buscasoap')->name('cadastro.buscasoap');
Route::post('inserirEmail', 'Soap\SoapController@validacrf')->name('cadastro.validacrf');
Route::get('pfs', 'Soap\SoapController@pfs');
Route::post('enviaemail', ['as' => 'cadastro.enviaemail', 'uses' => 'Soap\SoapController@enviaemail' ]);
//Route::get( 'enviaemail', 'Soap\SoapController@enviaemail')->name('cadastro.enviaemail');


//Route::get( 'admin2/user/roles', ['middleware'=> ['web'], function () {
//
//    return "Middleware role";
//}  ]);

Route::get( '/admin2', 'AdminController@index');

//TESTES DE LOGIN E PERFIL////////////////////////////////////////////////////////////


/***********************************************************
 * -------------------------------------------------------------------------
 *  Painel Administrador
 * -------------------------------------------------------------------------
 */
Route::group([ 'as' => 'admin.', 'prefix' => 'admin',  'middleware' => ['auth', 'IsAdmin']], function() {

    /**
    * Home
    */
    Route::get('/',['as' => 'home', function() {
        return View::make('admin::home');
    }]);

    /**
    * Artigos
    */
    Route::resource( 'artigos', 'Admin\ArtigoController' );
    Route::post('artigo/{id}/active', ['uses' => 'Admin\ArtigoController@active', 'as' => 'artigos.active']);

    /**
    * Banners
    */
    Route::resource( 'banners', 'Admin\BannerController' );

     /**
    * Bloqueios Temporários
    */
    Route::resource( 'bloqueios', 'Admin\BloqueiosController' );

    /**
    * Descontos
    */
    Route::resource( 'descontos', 'Admin\DescontoController' );
    Route::post('descontos/{id}/active', ['uses' => 'Admin\DescontoController@active', 'as' => 'descontos.active']);

    /**
    * Cargos
    */
    Route::resource( 'cargos', 'Admin\CargoController' );
    Route::post('cargo/{id}/active', ['uses' => 'Admin\CargoController@active', 'as' => 'cargos.active']);
    Route::post('cargo/{id}/activecv', ['uses' => 'Admin\CargoController@activecv', 'as' => 'cargos.activecv']);


    /**
    * Concursos
    */
    Route::resource( 'concursos', 'Admin\ConcursoController' );
    Route::post('concurso/{id}/active', ['uses' => 'Admin\ConcursoController@active', 'as' => 'concurso.active']);


    /**
    * Categorias
    */
    Route::resource( 'categorias', 'Admin\CategoriaController' );

    /**
    * Curriculos
    */
    Route::resource( 'curriculos', 'Admin\CurriculoController' );



    /**
    * Empresas
    */
    Route::resource( 'empresas', 'Admin\EmpresaController' );

     /**
    * Estatísticas
    */
    Route::resource( 'estatisticas', 'Admin\EstatisticasController' );


    /**
    * Linguas
    */
    Route::resource( 'linguas', 'Admin\LinguaController' );



    /**
    * Parceiros
    */
    Route::resource( 'parceiros', 'Admin\ParceiroController' );
    Route::post('parceiro/{id}/active', ['uses' => 'Admin\ParceiroController@active', 'as' => 'parceiro.active']);

    /**
    * Ramos
    */
    Route::resource( 'ramos', 'Admin\RamoController' );

    /**
    * Temas
    */
    Route::resource( 'temas', 'Admin\TemaController' );

     /**
    * Testmail
    */
    Route::get('testmail', ['as' => 'testmail', 'uses' => 'TestmailController@create' ]);
    Route::post('testmail', ['as' => 'testmail.store', 'uses' => 'TestmailController@store' ]);

    /**
    * Vagas
    */
    Route::resource( 'vagas', 'Admin\VagaController' );
    Route::post('vaga/{id}/active', ['uses' => 'Admin\VagaController@active', 'as' => 'vagas.active']);
    Route::post('vaga/{id}/disable', ['uses' => 'Admin\VagaController@disable', 'as' => 'vagas.disable']);

     /**
    * Peritos
    */
    Route::resource( 'peritos', 'Admin\PeritoController' );
    Route::get('peritos/excel/{type}', 'Admin\PeritoController@excel');
    Route::get('peritos/downloadExcel/{type}', 'Admin\PeritoController@downloadExcel');
    

         /**
    * Usuários
    */
    Route::resource( 'usuarios', 'Admin\UsuarioController' );
    Route::get('usuarios/downloadExcel/{type}', 'Admin\UsuarioController@downloadExcel');
    Route::post('usuarios/{id}/active', ['uses' => 'Admin\UsuarioController@active', 'as' => 'usuarios.active']);





});

//
//Route::group([ 'as' => 'farmaceutico.', 'prefix' => 'farmaceutico',  'middleware' => ['auth', 'IsFarmaceutico']], function() {
//
//    /**
//    * Home
//    */
//    Route::get('/',['as' => 'home', function() {
//        return View::make('farmaceutico::home');
//    }]);
//
//});
//
//
//Route::group([ 'as' => 'empresa.', 'prefix' => 'empresa',  'middleware' => ['auth', 'IsEmpresa']], function() {
//
//    /**
//    * Home
//    */

app/Http/Controllers/Admin/BloqueiosController.php
<?php

namespace App\Http\Controllers\Admin;

use App\BloqueiosTemporarios;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BloqueiosController extends Controller {

    /**
    *
    * Mostrar Linguas
    *
    **/
	public function index(Request $filters) {

        $bloqueios = BloqueiosTemporarios::orderBy('TT034CC004') -> paginate (30);


            return view( 'admin::bloqueios.index', compact('bloqueios'));


	}

    /**
    *
    * Cadastrar Lingua
    *
    **/
    public function create() {
        return View ( 'admin::bloqueios.create' );
    }

    /**
    *
    * Gravar Lingua
    *
    **/
    public function store( Request $request ) {

        $this -> validate( $request, BloqueiosTemporarios::$rules );

        // Dados do lingua
//        $lingua = new Lingua();
//        $lingua -> fill( $request -> all() );
//        $lingua -> save();
//
//        return redirect() -> back() -> with('success', 'Lingua cadastrado com sucesso');
    }

    /**
    *
    * Editar Lingua
    *
    **/
    public function edit( $id ) {
//        $lingua = Lingua::find( $id );
//        return View ('admin::linguas.edit', compact('lingua'));
    }

    /**
    *
    * Atualizar Lingua
    *
    **/
    public function update( Request $request, $id ) {

//        if ($lingua = Lingua::find($id)) {
//
//            $this -> validate( $request, Lingua::$rules );
//
//            // Dados do lingua
//            $lingua = Lingua::find($id);
//            $lingua -> fill($request -> all());
//            $lingua -> save();
//
//            return redirect() -> back() -> with('success', 'Lingua atualizado com sucesso');
//        }
//
//        return redirect() -> route('admin.linguas.index') -> with('alert', 'Lingua não encontrado');
    }

    /**
    *
    * Deletar Lingua
    *
    **/
    public function destroy($id){

//       if ($lingua = Lingua::find($id)) {
//
//            if (count($lingua -> idiomas)) {
//                return redirect() -> back() -> with('alert', 'Registro de idiomas relacionadas com o língua');
//            }
//
//            $lingua -> delete();
//
//            return redirect() -> route('admin.linguas.index') -> with('success', 'Língua deletada com sucesso');
//        }
//
//        return redirect() -> back() -> with('alert', 'Língua não encontrada');
    }
}

resources/views/admin/bloqueios/create.blade.php
<!-- layout Master -->
@extends('admin::app')

<!-- Título -->
@section('titulo') Cadastro de Bloqueios | Admin @stop

<!-- Conteúdo -->
@section('conteudo')

<!-- Título -->
<h2 class="m-3">Cadastro de Bloqueios</h2>
<!-- /Título -->

<!-- Mensagens de sucesso -->
@if ($message = Session::get('success'))
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <p class="mb-0">
        {{ $message }}
    </p>
</div>
@endif
<!-- /Mensagens de sucesso -->

<!-- Mensagens de erro -->
@if ( count( $errors ) > 0 )
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <p class="mb-0"> Confira os campos em destaque </p>
</div>
@endif
<!-- /Mensagens de erro -->

{{ Form::open(['route' => 'admin.bloqueios.store','method'=>'POST']) }}

<div class="card">
    <div class="card-block">

        <div class="title clearfix">
            <div class="title-form"><span class="cor-texto">Bloqueios</span></div>
        </div>

        <div class="row">
            <!-- Bloqueio -->
            <div class="col-12">
                <div class="form-group @if ( $errors -> has( 'TT034CC001' )) has-danger @endif">
                    {{ Form::label( 'TT034CC003', 'Texto do aviso *', ['class' => 'form-control-label' ]) }}
                    {{ Form::text
                        (
                            'TT034CC003',
                            null,

                            [
                                'class' => 'form-control',
                                'maxlength' => '500'
                            ]
                        )
                    }}

                    <!-- Erro -->
                    @if ($errors->has('TT034CC003'))
                    <div class="form-control-feedback">
                        {{ $errors->first( 'TT034CC003' ) }}
                    </div>
                    @endif
                    <!-- /Erro -->
                </div>
            </div>
            <!-- /Bloqueio -->
        </div>

        <div class="row mb-1">
            <div class="col-12">
                <p class="card-text text-uppercase"><strong>( * ) Campos obrigatórios</strong></p>
            </div>
        </div>

        <!-- Controle -->
        <div class="row">
            <div class="col-12 col-sm-3"></div>

            <!-- Voltar -->
            <div class="col-12 col-sm-3">
                <a class="btn btn-block btn-admin mb-xs-1" href="{{ URL::Route( 'admin.bloqueios.index' ) }}">
                    <i class="fa fa-arrow-left fa-2x" aria-hidden="true"></i>
                </a>
            </div>
            <!-- /Voltar -->

            <!-- Confirmar -->
            <div class="col-12 col-sm-3">
                {{ Form::button
                   (
                        '<i class="fa fa-check fa-2x" aria-hidden="true"></i>',

                        [
                            'class' => 'btn btn-block btn-admin',
                            'type' => 'submit'
                        ]
                    )
                }}
            </div>
            <!-- /Confirmar -->

            <div class="col-12 col-sm-3"></div>
        </div>
        <!-- /Controle -->
    </div>
</div>

{{ Form::close() }}

@stop

resources/views/admin/bloqueios/index.blade.php
<!-- layout Master -->
@extends('admin::app')

<!-- Título -->
@section('titulo') Bloqueios Temporários | Admin @stop

<!-- Conteúdo -->
@section('conteudo')

<!-- Novo -->
        <div class="float-left">
            <a class="btn btn-admin" href="{{ URL::Route( 'admin.bloqueios.create' ) }}">
                <i class="fa fa-plus fa-2x" aria-hidden="true"></i>
            </a>
        </div>
<!-- /Novo -->
<!-- Título -->
<h1 class="text-center">Bloqueios</h1>



<!-- Mensagens de sucesso -->
@if ($message = Session::get('success'))
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <p class="mb-0">
        {{ $message }}
    </p>
</div>
@endif
<!-- /Mensagens de sucesso -->

<!-- Mensagens de Alerta -->
@if ( $message = Session::get( 'alert' ))
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <p class="mb-0">{{ $message }}</p>
</div>
@endif
<!-- /Mensagens de Alerta -->
<!-- Buscas -->
<div class="card mb-3">
    <div class="card-block">
        <div class="row">

        </div>
    </div>
</div>
<!-- Buscas -->
<!-- Bloqueios -->
<section class="load-ajax">
    @include('admin::bloqueios.load')
</section>
<!-- /Bloqueios -->

@stop

resources/views/admin/bloqueios/load.blade.php
<!-- Bloqueios -->
<div class="card mb-3">
    <div class="card-block">
        <div class="title clearfix">
            <div class="title-form"><span class="cor-texto">Bloqueios</span></div>
        </div>
        <div class="table-responsive">
            <table class="table table-bordered">
                <tr>
                    <th> Código </th>
                    <th> Tipo </th>
                <th> Texto aviso </th>
                     <th> Início </th>
                      <th> Final </th>
                    <th></th>
                </tr>
                @foreach ( $bloqueios as $bloqueio )
                <tr>
                    <td>{{ $bloqueio -> TT034CC000 }}</td>
                    <td>{{ $bloqueio -> TT034CC001 }}</td>
                    <td>{{ $bloqueio -> TT034CC002 }}</td>

                    <td>{{ date_format( date_create( $bloqueio -> TT034CC003 ),'d/m/Y - h:m' ) }}</td>
                    <td>{{ date_format( date_create( $bloqueio -> TT034CC004 ),'d/m/Y - h:m' ) }}</td>
                    <td>
                        <!-- Controle -->
                        <div class="row">
                            <!-- Editar -->
                            <div class="col-12 col-sm-6">
                                <a class="btn btn-block btn-admin mb-2 mb-md-0" href="{{ route( 'admin.bloqueios.edit', $bloqueio -> idbloqueio )}}">
                                    <i class="fa fa-pencil-square-o fa-lg" aria-hidden="true"></i>
                                </a>
                            </div>
                            <!-- Editar -->

                            <!-- Deletar -->

                            <div class="col-12 col-sm-6">
                                {{ Form::open([ 'method' => 'Delete','route' => [ 'admin.bloqueios.destroy', $bloqueio -> idbloqueio ]]) }}
                                {{ Form::button
                                    (
                                        '<i class="fa fa-trash-o fa-lg" aria-hidden="true"></i>',

                                        [
                                            'class' => 'btn btn-block btn-admin',
                                            'type' => 'submit'
                                        ]
                                    )
                                }}
                                {{ Form::close() }}
                            </div>
                            <!-- Deletar -->
                        </div>
                        <!-- /Controle -->
                    </td>
                </tr>
                @endforeach
            </table>
        </div>
    </div>
</div>
<!-- /Bloqueios -->

<!-- Paginação -->
{{ $bloqueios -> links( 'partials.pagination' ) }}